### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by bestpika** [Revadike/SteamWebIntegration#45]
Hello, I have a few requests that I would like to ask you if you can implement.

1. Domain whitelist mode.
The current script only has domain blacklist mode, which makes me a bit awkward in using the above, I would like to ask if it is possible to add whitelist mode?
2. Show followed.
I hope the followed icon can be added.

Thank you.

**Comment by Revadike** [comment]
1. I don't think I will add this, since most relevant sites have their own addons/extensions that have some, if not all, of the features provided by SWI in some way. For example, ESGST for SteamGifts/SteamTrades. 
2. Please don't combine multiple feature requests in 1 issue, but make each their own issue.

Thanks for your suggestions!

**Comment by bestpika** [comment]
Then can I modify the source code and send you a PR?
