### ISSUE TITLE
Flag for DLCs

### ISSUE THREAD

**Issue by TrAnn3l** [Revadike/SteamWebIntegration#9]
It would be nice when you could show an indicator, whether the package is a dlc or not.

**Comment by Luckz** [comment]
What is your use case for this? Do you have a particular website that shows titles with Steam links but does not clarify which are DLC, or where is it useful?

So far nobody else asked for this (from what I can tell), and it's not extremely easy to add this here.

**Comment by TrAnn3l** [comment]
http://www.dailyindiegame.com was not showing wether the items where games or dlcs. They added it now, but the old dlcs are still not displayed correctly. If it is hard to add this feature then it doesn't need to be added. I thought it would just be a small tweak.

**Comment by Royalgamer06** [comment]
All DLC apps: https://steamdb.info/api/GetAppList/?apptype=4

**Comment by Revadike** [comment]
This could perhaps be done using barter.vg API.

**Comment by Denny-89** [comment]
I'd like to add something in case this DLC thing will ever get implemented -> it would be nice to show if you own the base game.

Example of the use case - you own thousands of games and obviously don't remember all of them; there are many giveaway sites and shops with high discounts on DLCs where you could get additional content for your games if only you knew which ones you own (checking one by one is too time consuming). 

I've solved this "problem" with adding all DLCs one by one to Steam's wishlist via SteamPrices.com missing DLC feature, but that's highly impractical since now every small change on my 4k wishlist literally takes forever or it doesn't even load (on Steam and SteamPrices) and i also get hundreds of Steam sale sites spam emails (they automatically import my list)...it's very annoying, but it helped me to find ~100 free and <$0.10 DLCs i don't own in less than a month.

**Comment by Revadike** [comment]
@Bartervg kindly provided us with [an endpoint](https://bartervg.com/browse/dlc/json/) that could realize this feature. Thank you, barter!
The feature is coming soon to SWI.
